# Generated by Django 2.1.7 on 2019-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosptial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
    ]
