# Generated by Django 2.1.5 on 2019-08-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_hosptial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.PositiveIntegerField()),
                ('district_inspector_name', models.CharField(max_length=50)),
                ('district_inspector_phone', models.PositiveIntegerField()),
                ('district_inspector_email', models.EmailField(max_length=254)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='location.District'),
            preserve_default=False,
        ),
    ]
