# Generated by Django 2.1.7 on 2019-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='f_dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='f_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='m_dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='m_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
