# Generated by Django 2.1.7 on 2019-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190831_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='f_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='m_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
