# Generated by Django 2.1.7 on 2019-08-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190831_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
