# Generated by Django 2.1.5 on 2019-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_parentuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='reminder_days',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentuser',
            name='reminder_frequency',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
