# Generated by Django 2.1.5 on 2019-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190831_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='reminder_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='reminder_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
