# Generated by Django 2.1.7 on 2019-08-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190831_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='location.Locality'),
        ),
    ]
