# Generated by Django 2.1.7 on 2019-08-31 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190831_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anmuser',
            name='locality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anmuserlocalities', to='location.Locality'),
        ),
        migrations.AlterField(
            model_name='anmuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anmusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clusteruser',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clusteruserscluster', to='location.Cluster'),
        ),
        migrations.AlterField(
            model_name='clusteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clusterusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='location.Locality'),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parentusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wardusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warduser',
            name='ward',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wardusersward', to='location.Ward'),
        ),
    ]
