# Generated by Django 2.1.7 on 2019-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190831_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmuser',
            name='phone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
