# Generated by Django 2.1.5 on 2019-08-31 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190831_2327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_anmuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='districtusersdistrict', to='location.District')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='districtusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
