# Generated by Django 2.1.7 on 2019-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190901_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentuser',
            name='reminder_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='parentuser',
            name='reminder_frequency',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
