# Generated by Django 2.1.7 on 2019-08-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190831_1943'),
        ('parent', '0005_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderANM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_anm', to='parent.Child')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_anm', to='account.ANMUser')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_anm', to='parent.Vaccine')),
            ],
        ),
    ]
