# Generated by Django 2.1.5 on 2019-08-31 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0006_reminderanm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=100)),
                ('pain', models.BooleanField()),
                ('swelling', models.BooleanField()),
                ('redness', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('irritability', models.BooleanField()),
                ('malaise', models.BooleanField()),
                ('crying', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AEFIs', to='parent.Child')),
            ],
        ),
    ]
