# Generated by Django 2.1.7 on 2019-08-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0008_auto_20190901_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['-pk']},
        ),
    ]
