# Generated by Django 2.1.7 on 2019-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0009_auto_20190901_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.FloatField(default=3.5),
            preserve_default=False,
        ),
    ]
